version: "3.8"

services:

  user-service:
    build: ./services/user-service
    image: pratham730/user-service:latest
    ports:
      - "3001:3001"

  booking-service:
    build: ./services/booking-service
    image: pratham730/booking-service:latest
    ports:
      - "3002:3002"

  recommendation-service:
    build: ./services/recommendation-service
    image: pratham730/recommendation-service:latest
    ports:
      - "3003:3003"

  gateway:
    build: ./gateway
    image: pratham730/gateway:latest
    ports:
      - "4000:3000"
    depends_on:
      - user-service
      - booking-service
      - recommendation-service

  frontend:
    build: ./frontend
    image: pratham730/frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - gateway
